# ALEATORIO.PY
# AUTOR: MARIA FERNANDA HERRERA TREJO
# FECHA DE CREACION: 19/09/2019

#PYTHON POSEE UNA GRAN VARIEDAD DE MODULOS, UN MODULO EN PYTHON ES UN ARCHIVO QUE CONTIENE CODIGOS CUYO PROPOSITO 
#ES SER REUTILIZADO POR OTROS DESARROLLOS SIN NECESIDAD DE ESCRIBIRLO NI COPIARLO.
#PARA PODER USAR DICHOS MODULOS ES NECESARIO IMPORTARLOS USANDO IMPORT.
import random

#SE ASIGNA UNA VARIABLE FLOAT( VALORES DECIMALES O CON PUNTO DECIMAL) Y SE LE ASIGNA UN VALOR CUALESQUIERA.

numero1=float(4.3)

# UNA FUNCION ES UN CONJUNTO DE INSTRUCCIONES PAAR LELVAR A CABO UNA TAREA.
# DICHA FUNCION DEBE DE SER DEFINIDA CON DEF, Y SE DEBE DE POSICIONAR A LA DERECHA, 
#ASI LO QUE ESTE POSICIONADO DE ESTA MANERA FORMARA PARTE DE DICHA FUNCION.
def miFuncion():
    #SE CONVIERTE A TYPO FLOAT EL NUMERO ALEATORIO GENERADO POR RANDOM OBVIAMENTE ESTE SOLO PODRA SER UTILIZADO 
    #SI SE IMPORTO RANDOM CON ANTERIORIDAD 

 numero2=float(random.randrange(1,10))
  #SE UTILIZAN LAS SUTITUCIONES PARA MOSTRAR EL RESULTADO FINAL 
 mensaje="La suma de {} y {} es {}"

 print(mensaje.format(numero1,numero2,numero1+numero2))


#FIN DE LA SENTENCIA, SE EJECUTA LA FUNCION DEFINIDA.
miFuncion()
