# ENTRADA.PY
# AUTOR: MARIA FERNANDA HERRERA TREJO 
# FECHA DE CREACION: 19/09/2019

entrada=input()
print(type(entrada))
#LA VARIABLE DE TYPO BOOLEANO CONTIENE LA INSTRUCION DE VERIFICAR SI EL RESULTADO DE LO CAPTURADO 
#ES DIGITO ENTERO, Y DE ENCONTRAR UN PUNTO INDICARA QUE SE TRATA DE UN NUMERO DECIMAL O DE TYPO FLOAT.
#SI LA  FUNCION FIND RETORNA UN -1 QUIERE DECIR QUE LO BUSCADO EN ESTE CASO ES UN PUNTO DECIMAL NO SE ENCONTRO.
#SI ES ENTERO ES TRUE, LO CAPTURADO ES ENTERO 
esEntero=(entrada.isdigit() and entrada.find(".")==-1)
if (esEntero):
#ESTA LINEA SE EHECUTARA SOLO SI LO CONTENIDO ES VERDADERO O TRUE
  print("Dato entero. ¡Muy bien!")

else:
#ESTA LIENA SE EJECUTARA SI LO CAPTURADO ES FALSO O FALSE
  print("Dato no es entero. intenta otra vez.")


