# MULTIPLO.PY
# AUTOR: FERNANDA HERRERA
# FECHA DE CREACION: 19/09/2019

#SE CAPTURA UN NUMERO Y SE GUARDA UNA VEZ QUE ES CONVERTIDO A INT
numero=int(input("Dame un numero entero: "))
#SE ALMACENA EN VALORES BOOLEANOS LA EVALUACION DE RESIDUALES. SI EL RESIDUAL ES 0
#QUIERE DECIR QUE EL NUMERO ES MULTIPLO
esMultiplo3=((numero%3)==0)
esMultiplo6=((numero%6)==0)
esMultiplo9=((numero%9)==0)
#CUANDO SE USA AND, SE RESUELVE POR VERDADERO SI TODAS LAS CONDICIONES SON VERDADERAS.CUANDO SE USA OR. 
# SE RESUELVE POR VERDADERP SI AL MENOS UNA CONDICION ES VERDADERA, LOS PARENTESIS LE INDICAN A PYTHON 
# QUE LAS PRIMERAS DOS CONDICIONES SON JUNTAS, Y LA TERCERA ES INDEPENDOENTE.


if ((esMultiplo3 and esMultiplo6) or esMultiplo9):
    print("correcto.")
else:
    print("incorrecto.")